services:
  postgres:
    image: polarizometro/bes-postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_LEGACY: ${POSTGRES_DB_LEGACY}
      POSTGRES_USER_LEGACY: ${POSTGRES_USER_LEGACY}
      POSTGRES_PASSWORD_LEGACY: ${POSTGRES_PASSWORD_LEGACY}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: polarizometro/bes-backend:latest
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST_LEGACY: ${DB_HOST_LEGACY}
      DB_PORT_LEGACY: ${DB_PORT_LEGACY}
      DB_NAME_LEGACY: ${POSTGRES_DB_LEGACY}
      DB_USER_LEGACY: ${POSTGRES_USER_LEGACY}
      DB_PASSWORD_LEGACY: ${POSTGRES_PASSWORD_LEGACY}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    image: polarizometro/bes-frontend:latest
    environment:
      VITE_API_HTTP_URL: ${VITE_API_HTTP_URL}
      VITE_API_WS_URL: ${VITE_API_WS_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge