# EJEMPLO, NO USAR
services:
  react-app:
    build:
      context: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true

  python-server:
    build:
      context: ./pol_measures_server
    ports:
      - "5000:5000"